name = input("Enter Your Name:")
age = int(input("Age:"))
city = input("Enter the City:")
course = input("Enter Course Name:")
print("**************")
print("   BIO CARD   ")
print("**************")
print("Name:",name)
print("Age :",age)
print("City:",city)
print("Course:",course)